### ISSUE TITLE
New Metal Collars

### ISSUE THREAD

**Issue by Ramen-atedSpaceBoi** [VEX-CAD/VEX-CAD-Inventor#6]
Still run into opening issue when collar is seen as an .IAM. in the CAD library I downloaded from the fixed version, but apparently it is an .ipt when I try to open it...

![Screenshot 2022-10-27 234121](https://user-images.githubusercontent.com/116993719/198863476-ac5d80f7-bf63-4b67-9ce3-de84e3c24894.png)

**Comment by liam-teale** [comment]
I get this issue too. This is issue occurs because the assembly has links to its component parts, which is not included in the library. There are 2 ways to resolve this

1.  Include the reference parts in the library
2. Break the links to the reference parts

either way this is going to require a new release @Unionjackjz1 @ylu12358

**Comment by ylu12358** [comment]
Pushed a fix, will be included in upcoming release 1.4.1
